name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: soap-axum
    steps:
      - uses: actions/checkout@v4
        with:
          path: soap-axum
      - uses: actions/checkout@v4
        with:
          repository: soaprs/soap
          ref: v0.4.0
          path: soaprs
      - uses: dtolnay/rust-toolchain@1.85.0
        with:
          components: clippy,rustfmt
      - run: cargo fmt --check
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test --all-targets --all-features
